#ifndef MAINWIDGET_HPP
#define MAINWIDGET_HPP

#include <QMainWindow>
#include <QSystemTrayIcon>
#if QT_VERSION >= 0x050000 && defined Q_OS_WIN
	#include <QAbstractNativeEventFilter>
	#define QT5_WINDOWS
#endif

#include <PlayClass.hpp>
#ifdef UPDATER
	#include <Updater.hpp>
#endif

class QFrame;
class QLabel;
class Slider;
class MenuBar;
class InfoDock;
class VideoDock;
class VolWidget;
class QToolButton;
class AboutWidget;
class PlaylistDock;
class SettingsWidget;
class QMPlay2Extensions;

class MainWidget : public QMainWindow
#ifdef QT5_WINDOWS
	, private QAbstractNativeEventFilter
#endif
{
	friend class QMPlay2GUIClass;
	Q_OBJECT
public:
	MainWidget(QPair<QStringList, QStringList> &);
	~MainWidget();
private slots:
	void detachFromPipe();

	void focusChanged(QWidget *, QWidget *);

	void processParam(const QString &, const QString &);

	void audioChannelsChanged();

	void updateWindowTitle(const QString &t = QString());
	void videoStarted();

	void togglePlay();
	void seek(int);
	void chStream(const QString &);
	void playStateChanged(bool);

	void volUpDown();
	void toggleMuteIcon();
	void actionSeek();
	void switchARatio();
	void resetARatio();
	void resetFlip();
	void resetRotate90();

	void visualizationFullScreen();
	void hideAllExtensions();
	void toggleVisibility();
	void createMenuBar();
	void trayIconClicked(QSystemTrayIcon::ActivationReason);
	void toggleCompactView();
	void toggleFullScreen();
	void showMessage(const QString &, const QString &, int, int);
	void statusBarMessage(const QString &, int ms);

	void openUrl();
	void openFiles();
	void openDir();
	void loadPlist();
	void savePlist();
	void saveGroup();
	void showSettings(const QString &);
	void showSettings();

	void itemDropped(const QString &, bool);
	void browseSubsFile();

	void setSeekSMaximum(int);
	void updatePos(int);
	void mousePositionOnSlider(int);

	void newConnection();
	void readSocket();

	void about();

#if !defined Q_OS_MAC && !defined Q_OS_ANDROID
	void hideMenu(bool);
#else
	void hideMenu(bool) {} //To avoid incorrect CPP file generated by MOC on Android
#endif
	void lockWidgets(bool);

	void hideDocksSlot();
	void delayedRestore(QByteArray data);

	void uncheckSuspend();
private:
	void savePlistHelper(const QString &, const QString &, bool);

	QMenu *createPopupMenu();

	void showToolBar(bool);
	void hideDocks();
	void restoreFocus();

	void mouseMoveEvent(QMouseEvent *);
	void leaveEvent(QEvent *);
	void closeEvent(QCloseEvent *);
	void changeEvent(QEvent *);
	void moveEvent(QMoveEvent *);
	void showEvent(QShowEvent *);
	void hideEvent(QHideEvent *);

#ifdef Q_OS_WIN
#if QT_VERSION < 0x050000
	bool winEvent(MSG *m, long *);
#else
	bool nativeEventFilter(const QByteArray &, void *m, long *);
#endif
#endif

	MenuBar *menuBar;
	QToolBar *mainTB;
	QStatusBar *statusBar;

	QFrame *vLine;
	QLabel *timeL, *stateL;

	VideoDock *videoDock;
	InfoDock *infoDock;
	PlaylistDock *playlistDock;

	Slider *seekS;
	VolWidget *volW;

	PlayClass playC;

	QSystemTrayIcon *tray;

	QByteArray dockWidgetState, fullScreenDockWidgetState;
	QList<QMPlay2Extensions *> visibleQMPlay2Extensions;
#ifndef Q_OS_ANDROID
	QRect savedGeo;
#endif

	SettingsWidget *settingsW;
	AboutWidget *aboutW;
	QWidget *lastFocusWidget;
	bool isCompactView, wasShow, fullScreen, seekSFocus;

#if !defined Q_OS_MAC && !defined Q_OS_ANDROID
	QAction *hideMenuAct;
#endif
	QAction *lockWidgetsAct;

#ifdef UPDATER
	Updater updater;
#endif
};

#endif //MAINWIDGET_HPP
