#!/bin/bash

cd "$(dirname "$0")"

echo Do you want to remove \"Makefile\", \"*.so*\" files, \"app\" and \"build\" directories form \"$PWD\" ? [n/y]
read choice
if [ ! -z $choice ]; then
	if [ $choice == 'Y' ] || [ $choice == 'y' ]; then
		rm -rf `find . | grep Makefile`
		rm -rf `find . | grep .Release`
		rm -rf `find . | grep .Debug`
		rm -rf `find . | grep build`
		rm -rf app x86_64-w64-mingw32 i686-w64-mingw32

		echo Cleaned!
		exit
	fi
fi

exit 1
