#!/bin/bash

_architectures="i686-w64-mingw32 x86_64-w64-mingw32"

for _arch in ${_architectures}; do
	$_arch-lrelease QMPlay2.pro &&
	mkdir -p app/lang &&
	mv lang/*.qm app/lang &&
	$_arch-qmake && 
	make -j8 && 
	rm app/*.a && 
	rm app/modules/*.a &&
	$_arch-strip -s `find app` 2> /dev/null ; true
	mv app $_arch &&
	make distclean
done
