#!/bin/sh

Threads=4
if [ ! -e $1 ]; then
	Threads=$1
fi

rm -r app/*

lrelease QMPlay2.pro
qmake && time make -j$Threads

BUILD_ERROR=$?

if [ $BUILD_ERROR != 0 ]; then
	echo Build failed!
else
	QMPlay2Dir=app/QMPlay2.app/Contents/MacOS
	mv app/bin/QMPlay2.app app || exit 1
	rmdir app/bin
	mv app/lib $QMPlay2Dir || exit 1
	mkdir -p $QMPlay2Dir/share/qmplay2/lang
	mv lang/*.qm $QMPlay2Dir/share/qmplay2/lang
	install_name_tool -change libqmplay2.dylib @executable_path/lib/libqmplay2.dylib $QMPlay2Dir/QMPlay2
	for dylib in $QMPlay2Dir/lib/qmplay2/modules/*.dylib; do
		install_name_tool -change libqmplay2.dylib @executable_path/lib/libqmplay2.dylib $dylib
	done
	cp ChangeLog $QMPlay2Dir/share/qmplay2
	echo Build complete!
fi

exit $BUILD_ERROR
