#!/bin/bash

Threads=4
if [ ! -e $1 ]; then
	Threads=$1
fi

lrelease QMPlay2.pro
qmake && time make -j$Threads

BUILD_ERROR=$?

if [ $BUILD_ERROR != 0 ]; then
	echo Build failed!
else
	QMPlay2Dir=app/QMPlay2.app/Contents/MacOS
	mv app/libqmplay2.dylib $QMPlay2Dir
	mv app/modules $QMPlay2Dir
	mkdir -p $QMPlay2Dir/lang
	mv lang/*.qm $QMPlay2Dir/lang
	cp ChangeLog $QMPlay2Dir
	install_name_tool -change libqmplay2.dylib @executable_path/libqmplay2.dylib $QMPlay2Dir/QMPlay2
	echo Build complete!
fi

exit $BUILD_ERROR
