#!/usr/bin/env bash

arch=`uname -m`
if [ -z $arch ] || [ $arch != 'x86_64' ] || [ ! -e /usr/lib64 ]; then
	libdir=lib
else
	libdir=lib64
fi

function do_mime_type
{
	cd src/gui/Unix || exit 1
	FILE_LIST=`ls x-*.xml` || exit 1

	MIME_PACKAGES='/usr/share/mime/packages'
	for MIME in $FILE_LIST
	do
		if [ $1 == 'install' ]
		then
			sudo cp --remove-destination -v $MIME $MIME_PACKAGES || exit 1
		elif [ $1 == 'uninstall' ]
		then
			sudo rm -v $MIME_PACKAGES/$MIME
		fi
	done

	echo "Updating MIME and desktop database"
	sudo update-desktop-database /usr/share/applications
	sudo update-mime-database /usr/share/mime
}

function copy_files
{
	sudo cp --remove-destination -v    app/bin/QMPlay2 /usr/bin || exit 1
	sudo cp --remove-destination -v    app/lib/libqmplay2.so /usr/$libdir || exit 1
	sudo cp --remove-destination -v -r app/lib/qmplay2 /usr/$libdir || exit 1
	sudo cp --remove-destination -v -r app/include /usr || exit 1
	sudo cp --remove-destination -v -r app/share /usr || exit 1

	sudo strip /usr/bin/QMPlay2 || exit 1
	sudo strip /usr/$libdir/qmplay2/modules/*.so || exit 1

	do_mime_type install
}

function remove_files
{
	sudo rm -v    /usr/bin/QMPlay2
	sudo rm -v    /usr/$libdir/libqmplay2.so
	sudo rm -v -r /usr/include/QMPlay2
	sudo rm -v    /usr/share/applications/QMPlay2*.desktop
	sudo rm -v    /usr/share/man/man1/QMPlay2.1.gz
	sudo rm -v    /usr/share/icons/QMPlay2.png
	sudo rm -v    /usr/share/icons/hicolor/128x128/apps/QMPlay2.png
	if [ -d /usr/share/kde4/apps/solid/actions ]; then
		sudo rm -v    /usr/share/kde4/apps/solid/actions/qmplay2-opencda.desktop
	elif [ -d /usr/share/apps/solid/actions ]; then
		sudo rm -v    /usr/share/apps/solid/actions/qmplay2-opencda.desktop
	fi
	sudo rm -v -r /usr/share/qmplay2
	sudo rm -v -r /usr/$libdir/qmplay2

	do_mime_type uninstall
}

export SYSTEM_BUILD=1
export NOTERM=1

if [ -z $1 ] || ( [ $1 != 'install' ] && [ $1 != 'uninstall' ] ); then
	echo "You must specify 'install' or 'uninstall'"
	exit 1
fi

if [ $1 == 'install' ]; then
	./compile_unix || exit $?
	copy_files && echo "Installation complete!" && exit
	echo "Installation failed!"
	exit 1
else
	remove_files
fi
