if(NOT SOLID_ACTIONS_INSTALL_PATH STREQUAL "None")
    if(NOT SOLID_ACTIONS_INSTALL_PATH)
        if(EXISTS "${CMAKE_INSTALL_PREFIX}/share/solid/actions")
            set(SOLID_ACTIONS_PATH "${CMAKE_INSTALL_PREFIX}/share/solid/actions")
        elseif(EXISTS "${CMAKE_INSTALL_PREFIX}/share/kde4/apps/solid/actions")
            set(SOLID_ACTIONS_PATH "${CMAKE_INSTALL_PREFIX}/share/kde4/apps/solid/actions")
        elseif(EXISTS "${CMAKE_INSTALL_PREFIX}/share/apps/solid/actions")
            set(SOLID_ACTIONS_PATH "${CMAKE_INSTALL_PREFIX}/share/apps/solid/actions")
        endif()
    else()
        set(SOLID_ACTIONS_PATH "${SOLID_ACTIONS_INSTALL_PATH}")
    endif()
    if(SOLID_ACTIONS_PATH)
        install(FILES Unix/solid-actions/QMPlay2-opencda.desktop DESTINATION "${SOLID_ACTIONS_PATH}")
    endif()
endif()
